### ISSUE TITLE
Create password reset api

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-server#1]
- create new api inside `/feature/auth` for password reset

**Comment by Pavankumar07s** [comment]
hey @harshmangalam  i want to work on this issue.😊

**Comment by harshmangalam** [comment]
Thanks @Pavankumar07s assigned to you

**Comment by Pavankumar07s** [comment]
Hey @harshmangalam  ,Thank you for the prompt response! I'm currently working on this issue and will keep you updated on the progress.
