### ISSUE TITLE
Configure eslint

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-server#25]
Configure eslint using https://github.com/antfu/eslint-config

**Comment by programmerraja** [comment]
Hey @harshmangalam  Hai

can i work on this?

**Comment by harshmangalam** [comment]
Sure @programmerraja

**Comment by programmerraja** [comment]
@harshmangalam can i know which node version is this porject using because i setup eslint with node 18

**Comment by harshmangalam** [comment]
We are not using node. Its a Bun project

**Comment by bgalek** [comment]
Eslint added :)
