### ISSUE TITLE
Add Interests api 

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-server#7]
Let's create interests api that will allow users to update their topics interests in topics feature

- Add api to follow and unfollow topic by id for authenticated user
- Add api to Fetch all followed topics by authenticated user

utilize `followingTopics` from users model and `followedByUsers` from topics model

For reference take a look into https://www.meetup.com/account/interests/

**Comment by TheAdich** [comment]
Hello @harshmangalam,

I am well-versed in Prisma ORM and proficient in writing queries with it. I can implement the API endpoint and fetch the desired results for the user. Could you please assign this issue to me? I am looking forward to contributing.

**Comment by harshmangalam** [comment]
Assigned @TheAdich
