### ISSUE TITLE
Add gender field in signup

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-server#8]
- Add gender field in prisma users schema
- Allow gender field in signup api schema and update in  users model.

**Comment by TheAdich** [comment]
hi @harshmangalam  I am well versed working with prismaORM and can easily configure your requirements . Could you assign this to me . Looking forward to Contribute

**Comment by harshmangalam** [comment]
@TheAdich thanks for your interest assigned this task to you.
